#spring.application.name=Spendly
#spring.data.mongodb.uri=mongodb://localhost:27017/spendlyDB

spring.data.mongodb.uri=mongodb+srv://shrestha_db:ShresthaDatabase9808@cluster0.drqyn44.mongodb.net/?appName=Cluster0
server.port=8080